---
- name: Disable SElinux and Firewalld
  hosts: all
  remote_user: ansible
  become: true
  become_method: sudo
 # gather_facts: false
  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Disable the firewalld service.
      service:
        name: firewalld
        state: stopped
        enabled: false
          
