---
- name: initialize docker swarm
  hosts: swarm-managers
  tasks:
    name: Create primary swarm manager
    shell: docker swarm init --advertise-addr {{ 192.168.33.151 }}
    when: "docker_info.stdout.find('Swarm: inactive') > 0"

    name: Get docker swarm manager ip
    copy:
      ontent: '{{ 192.168.33.151 }}'
      dest: '/tmp/dsm_ip'

    name: Get docker swarm manager token
    shell: docker swarm join-token -q manager
    register: swarm_manager_token
    copy:
      content: '{{ swarm_manager_token.stdout }}'
      dest: '/tmp/dsm_mt'

    name: Get docker swarm worker token
    shell: docker swarm join-token -q worker
    register: swarm_worker_token
    copy:
      content: '{{ swarm_worker_token.stdout }}'
      dest: '/tmp/dsm_wt'

