---
# tasks file for ntpclient
# list will be inserted in reverse order
- name: Adding lines into /etc/chrony.conf.
  lineinfile:
    dest: /etc/chrony.conf
    line: '{{ item }}'
    insertafter: 'server 3.centos.pool.ntp.org iburst'
    state: present
  with_items:
  - 'server 192.168.33.10 iburst'
  - 'server 192.168.33.11 iburst'
  - '# NTP SERVER IP'

- name: Commenting public servers /etc/chrony.conf
  replace:
    path: /etc/chrony.conf
    regexp: '^{{item.from}}'
    replace: '#{{item.from}}'
  with_items:
    - {from: 'server 0.centos.pool.ntp.org iburst'}
    - {from: 'server 1.centos.pool.ntp.org iburst'}
    - {from: 'server 2.centos.pool.ntp.org iburst'}
    - {from: 'server 3.centos.pool.ntp.org iburst'}


- name: Systemctl enable chronyd
  systemd:
    name: chronyd
    enabled: yes

- name: Systemctl restart chronyd
  systemd: 
    state: restarted
    name: chronyd