---
- name: Configure chrony Server
  tags: chrony_server_config
  hosts: NTP
  become: true
  roles:
    - ntpservers

- name: Configure FTP server
  tags: ftp_server_config
  hosts: FTP
  become: true
  roles:
    - ftpserver

- name: Configure FTP client
  tags: ftp_client_config
  hosts: NTP DNSMASTER DNSWORKER NFS DB WEBSERVER LOADBALANCER NAGIOS LDAP DOCKERMASTER DOCKERWORKER localhost
  become: true
  roles:
    - ftpclient

- name: Configure NTP client
  tags: ntp_client_config
  hosts: DNSMASTER DNSWORKER NFS DB WEBSERVER LOADBALANCER NAGIOS LDAP DOCKERWORKER DOCKERMASTER localhost
  become: true
  roles:
    - ntpclient



 

   