---
- name: Setup dns master
 # remote_user: root
  hosts: dnsmaster11
  become: yes
  #become_method: sudo 
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Disable the firewalld service.
    service:
      name: firewalld
      state: stopped
      enabled: no

  - name: Install packages
    yum:
      name:
        - bind
        - bind-utils
        - epel-release
      state: latest

  - name: Configure dns master
    template:
      src: dnsm.j2
      dest: /etc/named.conf
      owner: root
      group: named

  - name: create ziyotek1.flz 
    file: 
      path: /var/named/ziyotek1.flz
      state: touch
      owner: root
      group: named

  - name: copying .flz file
    template:
      src:  flz.j2
      dest: /var/named/ziyotek1.flz
      owner: root
      group: named
      
  - name: create ziyotek1.rlz 
    file: 
      path: /var/named/ziyotek1.rlz
      state: touch
      owner: root
      group: named 

  - name: copying .rlz file
    template:
      src: rlz.j2
      dest: /var/named/ziyotek1.rlz
      owner: root
      group: named
      
  - name: Install packages
    hosts: dns-clients
    yum:
      name:
        - bind
        - bind-utils
        - epel-release
        - man
        - man-pages
        - mlocate
        - sysstat
        - bash-completion
      state: latest 

  - name: Enable sysstat
    service:
      name: sysstat
      enabled: true
      state: started

  - name: Start named
    service:
      name: named
      enabled: yes
      state: restarted