---
- name: Adding DNS server ip to configuration file 
  hosts: dns-clients localhost
  become: true 
  become_method: sudo 
  tasks:
    - replace:
        path: /etc/resolv.conf
        regexp: '8.8.8.8'
        replace: '192.168.33.12'
        backup: yes
    - lineinfile:
        path: /etc/resolv.conf 
        line: "nameserver 192.168.33.13"
        state: present
        backup: yes  
    - lineinfile:
        path: /etc/resolv.conf 
        line: "nameserver 192.168.33.14"
        state: present
        backup: yes  
- name: configuration file 
  tags: conf
  hosts: dns-clients 
  become: true 
  become_method: sudo 
  tasks:
    - lineinfile:
        path: /etc/resolv.conf 
        line: "nameserver 192.168.33.1"
        state: absent
        backup: yes
   
