---
- name: Adding DNS server ip to configuration file 
  hosts: dns-clients
  become: true 
  become_method: sudo 
  tasks:
    - replace:
        path: /etc/resolv.conf
        regexp: '8.8.8.8'
        replace: '192.168.33.125'
        backup: yes
    - lineinfile:
        path: /etc/resolv.conf 
        line: "nameserver 192.168.33.131"
        state: present
        backup: yes  
    - lineinfile:
        path: /etc/resolv.conf 
        line: "nameserver 192.168.33.130"
        state: present
        backup: yes  