---
- name: setup pre-requisites
  hosts: all
  remote_user: ansible
  become: true
  become_method: sudo
  gather_facts: false
  roles:
    - install-common-packages

- name: Disable SElinux and Firewall
  hosts: docker-nodes
  roles:
    - disable-selinux-firewalld 

- name: Remove older version of docker
  hosts: docker-nodes
  roles:
    - remove-old-version

- name: install docker
  hosts: docker-nodes
  roles:
    - docker-installation

- name: initialize docker swarm
  hosts: swarm-managers
  roles:
   - swarm-init

- name: add workers to the swarm
  hosts: swarm-workers
  roles:
    - swarm-join


