---
- name: Updating ansible.cfg file.
  become: yes
  hosts: localhost
  tasks:
    - name: Adding Inventory PATH into the ansible.cfg file.
      # Manage lines in text files
      lineinfile:
        # Whether the line should be there or not.
        state: present
        # The path of the file to modify.
        path: /etc/ansible/ansible.cfg
        # Will check the string in every line of the file.
        regexp: '^inventory'
        # The line to insert/replace into the file.
        line: 'inventory   = /ansible/project/docker-project/inventory.ini' 
        # EOF for inserting the line at the end of the file.
        insertafter: EOF 
        # BOF for inserting the line at the beginning of the file.
        #insertbefore: BOF


    - name: Adding ROLES PATH into the ansible.cfg file.
      lineinfile:
        state: present
        path: /etc/ansible/ansible.cfg
        regexp: '^roles_path '
        line: 'roles_path    = /ansible/project/docker-project/roles'
        insertafter: EOF 
        #insertbefore: BOF