---
  - name: Create Docker Swarm Service
    hosts: docker-nodes
    become: yes
    remote_user: ansible
    become_method: sudo
    gather_facts: false
    tasks:
    # - name: deploy nginx docker container
    #   docker_container:
    #     image: httpd:stable
    #     name: nginx
    #     state: started
    #     auto_remove: true
        # ports:
        #   - "8080:80"
    - name: test
      shell:
        cmd: docker service create -p 80:80 --name webservice --replicas 3 httpd
    
    

  # - name: Docker service ls
  #   shell: docker service ls | grep -v ID test | cut -d " " -f1
  #   register: myservice

  # - name: Docker exec
  #   shell: docker service ls | grep -v ID test | cut -d " " -f1
  #   register: myservice

  # - name: Get info from a service
  # docker_swarm_service_info:
  #   name: myservice
  # register: result