---
  - name: Add Workers to the Swarm
    docker_swarm:
      state: join
      advertise_addr: "{{ ansible_host }}"
      join_token: "{{ hostvars['prdx-dmaster11']['worker_token']['stdout'] }}"
      remote_addrs: [ "{{ hostvars['prdx-dmaster11']['ansible_default_ipv4']['address'] }}:2377" ]
    tags: swarm
