- name: Install chronyd Server
  yum:
    name: chrony
    
- name: Adding lines into /etc/chrony.conf
  lineinfile:
    dest: /etc/chrony.conf
    line: '{{ item.new_line }}'
    insertafter: '{{ item.main_line }}'
    state: present
  with_items:
  - {main_line: '# Serve time even if not synchronized to a time source.', new_line: 'local stratum 10'}
  - {main_line: '# Allow NTP client access from local network', new_line: 'allow 192.168.33.0/24'}

- name: Systemctl enable chronyd
  systemd:
    name: chronyd
    enabled: yes

- name: Systemctl restart chronyd
  systemd: 
    state: restarted
    name: chronyd

- name: Systemctl stop firewalld
  tags: run_this
  systemd:
    name: firewalld
    state: stopped

- name: Disable SElinux
  replace:
    path: /etc/selinux/config
    regexp: 'SELINUX=enforcing'
    replace: 'SELINUX=disabled'