---
  - name: Create Docker Swarm Service
    hosts: swarm-managers
    become: yes
    remote_user: ansible
    become_method: sudo
    gather_facts: false
    tasks:
    - name: test
      shell:
        cmd: "docker service create -p 80:80 --name webservice --replicas 3 httpd"
    