---
- name: Adding IPs and hostname in the /etc/hosts file.
  become: yes
  hosts: localhost
  tasks:
    - name: Add Node Group
      # This module will insert/update/remove a block of multi-line text surro
      blockinfile:
        state: present
        path: /etc/ansible/hosts
        block: |
          [docker-nodes]
          prdx-dmaster11 ansible_host=192.168.33.151
          prdx-dworker11 ansible_host=192.168.33.152
          prdx-dworker21 ansible_host=192.168.33.153

          [swarm-managers]
          prdx-dmaster11 ansible_host=192.168.33.151

          [swarm-workers]
          prdx-dworker11 ansible_host=192.168.33.152
          prdx-dworker21 ansible_host=192.168.33.153
