---
- name: Removing IPs and hostnames from the /etc/hosts file.
  become: yes
  hosts: localhost
  tasks:
    - name: Remove Swarm Master
      # Manage lines in text files
      lineinfile:
        # The path of the file to modify.
        path: /etc/hosts
         # Will check the string in every line of the file.
        regexp: '^192.168.33.151'
        # Whether the line should be there or not.
        state: absent
      
    - name: Remove Swarm Worker1
      lineinfile:
         # The path of the file to modify.
        path: /etc/hosts
         # Will check the string in every line of the file.
        regexp: '^192.168.33.152'
        # Whether the line should be there or not.
        state: absent

    - name: Remove Swarm Worker2
      lineinfile:
         # The path of the file to modify.
        path: /etc/hosts
         # Will check the string in every line of the file.
        regexp: '^192.168.33.153'
        # Whether the line should be there or not.
        state: absent
