---
- name: Setup dns master
  hosts: dns-master
  become: yes
  roles:
    - disable-se-fw
    - install-packages

- name: Setup localhost
  hosts: localhost
  become: yes
  roles:
    - disable-se-fw
    - install-packages

- name: Setup dns master
  hosts: dns-master
  tasks:
  - name: Configure dns master
    template:
      src: dnsm.j2
      dest: /etc/named.conf
      owner: root
      group: named

  - name: create ziyotek1.flz 
    file: 
      path: /var/named/ziyotek1.flz
      state: touch
      owner: root
      group: named

  - name: copying .flz file
    template:
      src:  flz.j2
      dest: /var/named/ziyotek1.flz
      owner: root
      group: named
      
  - name: create ziyotek1.rlz 
    file: 
      path: /var/named/ziyotek1.rlz
      state: touch
      owner: root
      group: named 

  - name: copying .rlz file
    template:
      src: rlz.j2
      dest: /var/named/ziyotek1.rlz
      owner: root
      group: named
      
  - name: Start named
    service:
      name: named
      enabled: yes
      state: restarted

- name: Install packages on dns-slaves
  hosts: dns-slave1, dns-slave2
  become: yes
  roles:
    - disable-se-fw
    - install-packages

- name: Setup dns-slave1
  hosts: dns-slave1
  become: yes  
  tasks:
  - name: Configure dns slave1
    template:
      src: dnss1.j2
      dest: /etc/named.conf
      owner: root
      group: named
  - name: Start named
    service:
      name: named
      enabled: yes
      state: restarted

- name: Setup dns-slave2
  hosts: dns-slave2
  become: yes  
  tasks:
  - name: Configure dns slave1
    template:
      src: dnss1.j2
      dest: /etc/named.conf
      owner: root
      group: named
  - name: Start named
    service:
      name: named
      enabled: yes
      state: restarted      

- name: Adding DNS server ip to configuration file dns-slve1 
  hosts: dns-slave1
  become: true 
  become_method: sudo 
  tasks:
    - replace:
        path: /etc/resolv.conf
        regexp: '8.8.8.8'
        replace: '192.168.33.13'
        backup: yes
    - lineinfile:
        path: /etc/resolv.conf 
        line: "nameserver 192.168.33.12"
        state: present
        backup: yes  
      
- name: Adding DNS server ip to configuration file  dns-slave2
  hosts: dns-slave2
  become: true 
  become_method: sudo 
  tasks:
    - replace:
        path: /etc/resolv.conf
        regexp: '8.8.8.8'
        replace: '192.168.33.14'
        backup: yes
    - lineinfile:
        path: /etc/resolv.conf 
        line: "nameserver 192.168.33.12"
        state: present
        backup: yes  
             
