---
# Playbook to install nagios server, clients and
# generate service checks based on Ansible inventory

- hosts: all
  remote_user: "{{ ansible_system_user }}"
  tasks: []

# role for nagios clients via NRPE
- hosts: all
  remote_user: "{{ ansible_system_user }}"
  roles:
    - nagios_client
    - disable-se-fw

# role for nagios server
- hosts: nagios
  remote_user: "{{ ansible_system_user }}"
  roles:
    - disable-se-fw
    - nagios
    - instructions
