---
  - name: Install Commom Packages
    become: true
    yum: 
      name:
        - net-tools
        - bind
        - bind-utils
        - epel-release 
        - man
        - man-pages
        - mlocate
        - sysstat
        - bash-completion
      state: latest 
  - name: Enable sysstat
    service:
      name: sysstat
      enabled: true
      state: started