---
  - name: Install autofs
    yum: 
      name: autofs
      state: latest
  - name: Create a mountable directory if it does not exist
    file:
      path: /share # Directory that you want to share
      state: directory
      owner: ansible
      group: ansible
      mode: '0775'

  - name: Master Map file
    lineinfile:
      path: /etc/auto.master.d/ldap.autofs
      line: /share /etc/auto.ldap
      create: yes

  - name: reload autofs
    service:
      name: autofs
      state: enabled

  - name: restart autofs
    service:
      name: autofs
      state: restarted

  - name: Indirect wildcard Maps
    lineinfile:
      path: /etc/auto.ldap
      line: '* -rw,sync 192.168.33.23:/home/&'
      create: yes